# Generated by Django 2.2 on 2020-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200420_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
