# Generated by Django 2.2 on 2020-04-21 19:32

from django.db import migrations, models
import django.utils.timezone
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='author_email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[products.validators.validate_author_email]),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title is not unique, please try again'}, help_text='Must be a unique title', max_length=255, unique=True, verbose_name='Product Title'),
        ),
    ]
